import {
    Activity,
    AirVent,
    Airplay,
    AlarmClock,
    AlertCircle,
    AlertOctagon,
    AlertTriangle,
    AlignCenter,
    AlignJustify,
    AlignLeft,
    AlignRight,
    ArrowDown,
    ArrowDownCircle,
    ArrowDownLeft,
    ArrowDownRight,
    ArrowLeft,
    ArrowLeftCircle,
    ArrowRight,
    ArrowRightCircle,
    ArrowUp,
    ArrowUpCircle,
    ArrowUpLeft,
    ArrowUpRight,
    AtSign,
    Award,
    Banknote,
    BarChart,
    BarChart2,
    Battery,
    BatteryCharging,
    Bell,
    Bluetooth,
    Bold,
    Book,
    Bookmark,
    Box,
    Briefcase,
    Brush,
    Bug,
    Cake,
    Calendar,
    Camera,
    Cast,
    Check,
    CheckCircle,
    CheckSquare,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Chrome,
    Circle,
    Clipboard,
    ClipboardList,
    Clock,
    Cloud,
    CloudDrizzle,
    CloudLightning,
    CloudOff,
    CloudRain,
    CloudSnow,
    Code,
    Codepen,
    Coffee,
    Columns,
    Command,
    Compass,
    Contact,
    Contrast,
    Copy,
    Copyright,
    CreditCard,
    Crop,
    Crosshair,
    Database,
    Disc,
    Divide,
    DivideCircle,
    DivideSquare,
    DollarSign,
    Download,
    DownloadCloud,
    Dribbble,
    Droplet,
    Edit,
    Edit2,
    Edit3,
    ExternalLink,
    Eye,
    EyeOff,
    Facebook,
    FastForward,
    Feather,
    File,
    Film,
    Filter,
    Flag,
    Flame,
    Flashlight,
    Folder,
    FolderMinus,
    FolderPlus,
    Frown,
    Gift,
    GitBranch,
    GitCommit,
    GitMerge,
    GitPullRequest,
    Github,
    Gitlab,
    Globe,
    GraduationCap,
    Grid,
    HardDrive,
    Hash,
    Headphones,
    Heart,
    HelpCircle,
    Hexagon,
    Home,
    Image,
    Inbox,
    Info,
    Instagram,
    Italic,
    Key,
    Layers,
    Layout,
    LifeBuoy,
    Link,
    Link2,
    Linkedin,
    List,
    Loader2,
    Locate,
    Lock,
    LogOut,
    Mail,
    Map,
    MapPin,
    Maximize,
    Maximize2,
    Meh,
    Menu,
    MessageCircle,
    MessageSquare,
    Mic,
    MicOff,
    Minimize,
    Minimize2,
    Minus,
    MinusCircle,
    MinusSquare,
    Monitor,
    Moon,
    MoreHorizontal,
    MoreVertical,
    MousePointer,
    Move,
    Music,
    Navigation,
    Navigation2,
    Octagon,
    Package,
    Paperclip,
    Pause,
    PauseCircle,
    PenTool,
    Percent,
    Phone,
    PhoneCall,
    PhoneForwarded,
    PhoneIncoming,
    PhoneMissed,
    PhoneOff,
    PhoneOutgoing,
    PieChart,
    Pin,
    Play,
    PlayCircle,
    Plus,
    PlusCircle,
    PlusSquare,
    Podcast,
    Power,
    Printer,
    Puzzle,
    QrCode,
    Radio,
    Redo,
    RefreshCcw,
    RefreshCw,
    Repeat,
    Rewind,
    Rocket,
    RotateCcw,
    RotateCw,
    Rss,
    Save,
    ScanLine,
    Scissors,
    Search,
    Send,
    Server,
    Settings,
    Share,
    Shield,
    ShoppingCart,
    Shuffle,
    Sidebar,
    Signal,
    SkipBack,
    SkipForward,
    Slack,
    Slash,
    Sliders,
    Smartphone,
    Smile,
    Snowflake,
    SortAsc,
    SortDesc,
    Speaker,
    Star,
    StopCircle,
    Sun,
    Sunrise,
    Sunset,
    Tablet,
    Tag,
    Target,
    Terminal,
    Thermometer,
    ThumbsDown,
    ThumbsUp,
    Ticket,
    Timer,
    ToggleLeft,
    ToggleRight,
    Trash2,
    TrendingDown,
    TrendingUp,
    Triangle,
    Truck,
    Tv,
    Twitch,
    Twitter,
    Type,
    Underline,
    Undo,
    Unlock,
    Upload,
    UploadCloud,
    Usb,
    User,
    Users,
    Video,
    VideoOff,
    Voicemail,
    Volume1,
    Volume2,
    VolumeX,
    Wallet,
    Watch,
    Webcam,
    Wifi,
    WifiOff,
    Wind,
    Youtube,
    Zap,
    ZoomIn,
    ZoomOut,
} from 'lucide-react';

export const icons = [
    { name: 'Home', icon: Home },
    { name: 'User', icon: User },
    { name: 'Users', icon: Users },
    { name: 'Settings', icon: Settings },
    { name: 'Bell', icon: Bell },
    { name: 'Folder', icon: Folder },
    { name: 'File', icon: File },
    { name: 'ClipboardList', icon: ClipboardList },
    { name: 'List', icon: List },
    { name: 'Calendar', icon: Calendar },
    { name: 'Inbox', icon: Inbox },
    { name: 'LogOut', icon: LogOut },
    { name: 'Trash2', icon: Trash2 },
    { name: 'BarChart', icon: BarChart },
    { name: 'HelpCircle', icon: HelpCircle },
    { name: 'Activity', icon: Activity },
    { name: 'AirVent', icon: AirVent },
    { name: 'Airplay', icon: Airplay },
    { name: 'AlarmClock', icon: AlarmClock },
    { name: 'AlertCircle', icon: AlertCircle },
    { name: 'AlertOctagon', icon: AlertOctagon },
    { name: 'AlertTriangle', icon: AlertTriangle },
    { name: 'AlignCenter', icon: AlignCenter },
    { name: 'AlignJustify', icon: AlignJustify },
    { name: 'AlignLeft', icon: AlignLeft },
    { name: 'AlignRight', icon: AlignRight },
    { name: 'ArrowDown', icon: ArrowDown },
    { name: 'ArrowDownCircle', icon: ArrowDownCircle },
    { name: 'ArrowDownLeft', icon: ArrowDownLeft },
    { name: 'ArrowDownRight', icon: ArrowDownRight },
    { name: 'ArrowLeft', icon: ArrowLeft },
    { name: 'ArrowLeftCircle', icon: ArrowLeftCircle },
    { name: 'ArrowRight', icon: ArrowRight },
    { name: 'ArrowRightCircle', icon: ArrowRightCircle },
    { name: 'ArrowUp', icon: ArrowUp },
    { name: 'ArrowUpCircle', icon: ArrowUpCircle },
    { name: 'ArrowUpLeft', icon: ArrowUpLeft },
    { name: 'ArrowUpRight', icon: ArrowUpRight },
    { name: 'AtSign', icon: AtSign },
    { name: 'Award', icon: Award },
    { name: 'Banknote', icon: Banknote },
    { name: 'BarChart2', icon: BarChart2 },
    { name: 'Battery', icon: Battery },
    { name: 'BatteryCharging', icon: BatteryCharging },
    { name: 'Bluetooth', icon: Bluetooth },
    { name: 'Bold', icon: Bold },
    { name: 'Book', icon: Book },
    { name: 'Bookmark', icon: Bookmark },
    { name: 'Box', icon: Box },
    { name: 'Briefcase', icon: Briefcase },
    { name: 'Brush', icon: Brush },
    { name: 'Bug', icon: Bug },
    { name: 'Cake', icon: Cake },
    { name: 'Camera', icon: Camera },
    { name: 'Cast', icon: Cast },
    { name: 'Check', icon: Check },
    { name: 'CheckCircle', icon: CheckCircle },
    { name: 'CheckSquare', icon: CheckSquare },
    { name: 'ChevronDown', icon: ChevronDown },
    { name: 'ChevronLeft', icon: ChevronLeft },
    { name: 'ChevronRight', icon: ChevronRight },
    { name: 'ChevronUp', icon: ChevronUp },
    { name: 'Chrome', icon: Chrome },
    { name: 'Circle', icon: Circle },
    { name: 'Clipboard', icon: Clipboard },
    { name: 'Clock', icon: Clock },
    { name: 'Cloud', icon: Cloud },
    { name: 'CloudDrizzle', icon: CloudDrizzle },
    { name: 'CloudLightning', icon: CloudLightning },
    { name: 'CloudOff', icon: CloudOff },
    { name: 'CloudRain', icon: CloudRain },
    { name: 'CloudSnow', icon: CloudSnow },
    { name: 'Code', icon: Code },
    { name: 'Codepen', icon: Codepen },
    { name: 'Coffee', icon: Coffee },
    { name: 'Columns', icon: Columns },
    { name: 'Command', icon: Command },
    { name: 'Compass', icon: Compass },
    { name: 'Contact', icon: Contact },
    { name: 'Contrast', icon: Contrast },
    { name: 'Copy', icon: Copy },
    { name: 'Copyright', icon: Copyright },
    { name: 'CreditCard', icon: CreditCard },
    { name: 'Crop', icon: Crop },
    { name: 'Crosshair', icon: Crosshair },
    { name: 'Database', icon: Database },
    { name: 'Disc', icon: Disc },
    { name: 'Divide', icon: Divide },
    { name: 'DivideCircle', icon: DivideCircle },
    { name: 'DivideSquare', icon: DivideSquare },
    { name: 'DollarSign', icon: DollarSign },
    { name: 'Download', icon: Download },
    { name: 'DownloadCloud', icon: DownloadCloud },
    { name: 'Dribbble', icon: Dribbble },
    { name: 'Droplet', icon: Droplet },
    { name: 'Edit', icon: Edit },
    { name: 'Edit2', icon: Edit2 },
    { name: 'Edit3', icon: Edit3 },
    { name: 'ExternalLink', icon: ExternalLink },
    { name: 'Eye', icon: Eye },
    { name: 'EyeOff', icon: EyeOff },
    { name: 'Facebook', icon: Facebook },
    { name: 'FastForward', icon: FastForward },
    { name: 'Feather', icon: Feather },
    { name: 'Film', icon: Film },
    { name: 'Filter', icon: Filter },
    { name: 'Flag', icon: Flag },
    { name: 'Flame', icon: Flame },
    { name: 'Flashlight', icon: Flashlight },
    { name: 'FolderMinus', icon: FolderMinus },
    { name: 'FolderPlus', icon: FolderPlus },
    { name: 'Frown', icon: Frown },
    { name: 'Gift', icon: Gift },
    { name: 'GitBranch', icon: GitBranch },
    { name: 'GitCommit', icon: GitCommit },
    { name: 'GitMerge', icon: GitMerge },
    { name: 'GitPullRequest', icon: GitPullRequest },
    { name: 'Github', icon: Github },
    { name: 'Gitlab', icon: Gitlab },
    { name: 'Globe', icon: Globe },
    { name: 'GraduationCap', icon: GraduationCap },
    { name: 'Grid', icon: Grid },
    { name: 'HardDrive', icon: HardDrive },
    { name: 'Hash', icon: Hash },
    { name: 'Headphones', icon: Headphones },
    { name: 'Heart', icon: Heart },
    { name: 'Hexagon', icon: Hexagon },
    { name: 'Image', icon: Image },
    { name: 'Info', icon: Info },
    { name: 'Instagram', icon: Instagram },
    { name: 'Italic', icon: Italic },
    { name: 'Key', icon: Key },
    { name: 'Layers', icon: Layers },
    { name: 'Layout', icon: Layout },
    { name: 'LifeBuoy', icon: LifeBuoy },
    { name: 'Link', icon: Link },
    { name: 'Link2', icon: Link2 },
    { name: 'Linkedin', icon: Linkedin },
    { name: 'Loader2', icon: Loader2 },
    { name: 'Locate', icon: Locate },
    { name: 'Lock', icon: Lock },
    { name: 'Mail', icon: Mail },
    { name: 'Map', icon: Map },
    { name: 'MapPin', icon: MapPin },
    { name: 'Maximize', icon: Maximize },
    { name: 'Maximize2', icon: Maximize2 },
    { name: 'Meh', icon: Meh },
    { name: 'Menu', icon: Menu },
    { name: 'MessageCircle', icon: MessageCircle },
    { name: 'MessageSquare', icon: MessageSquare },
    { name: 'Mic', icon: Mic },
    { name: 'MicOff', icon: MicOff },
    { name: 'Minimize', icon: Minimize },
    { name: 'Minimize2', icon: Minimize2 },
    { name: 'Minus', icon: Minus },
    { name: 'MinusCircle', icon: MinusCircle },
    { name: 'MinusSquare', icon: MinusSquare },
    { name: 'Monitor', icon: Monitor },
    { name: 'Moon', icon: Moon },
    { name: 'MoreHorizontal', icon: MoreHorizontal },
    { name: 'MoreVertical', icon: MoreVertical },
    { name: 'MousePointer', icon: MousePointer },
    { name: 'Move', icon: Move },
    { name: 'Music', icon: Music },
    { name: 'Navigation', icon: Navigation },
    { name: 'Navigation2', icon: Navigation2 },
    { name: 'Octagon', icon: Octagon },
    { name: 'Package', icon: Package },
    { name: 'Paperclip', icon: Paperclip },
    { name: 'Pause', icon: Pause },
    { name: 'PauseCircle', icon: PauseCircle },
    { name: 'PenTool', icon: PenTool },
    { name: 'Percent', icon: Percent },
    { name: 'Phone', icon: Phone },
    { name: 'PhoneCall', icon: PhoneCall },
    { name: 'PhoneForwarded', icon: PhoneForwarded },
    { name: 'PhoneIncoming', icon: PhoneIncoming },
    { name: 'PhoneMissed', icon: PhoneMissed },
    { name: 'PhoneOff', icon: PhoneOff },
    { name: 'PhoneOutgoing', icon: PhoneOutgoing },
    { name: 'PieChart', icon: PieChart },
    { name: 'Pin', icon: Pin },
    { name: 'Play', icon: Play },
    { name: 'PlayCircle', icon: PlayCircle },
    { name: 'Plus', icon: Plus },
    { name: 'PlusCircle', icon: PlusCircle },
    { name: 'PlusSquare', icon: PlusSquare },
    { name: 'Podcast', icon: Podcast },
    { name: 'Power', icon: Power },
    { name: 'Printer', icon: Printer },
    { name: 'Puzzle', icon: Puzzle },
    { name: 'QrCode', icon: QrCode },
    { name: 'Radio', icon: Radio },
    { name: 'ScanLine', icon: ScanLine },
    { name: 'Redo', icon: Redo },
    { name: 'RefreshCcw', icon: RefreshCcw },
    { name: 'RefreshCw', icon: RefreshCw },
    { name: 'Repeat', icon: Repeat },
    { name: 'Rewind', icon: Rewind },
    { name: 'Rocket', icon: Rocket },
    { name: 'RotateCcw', icon: RotateCcw },
    { name: 'RotateCw', icon: RotateCw },
    { name: 'Rss', icon: Rss },
    { name: 'Save', icon: Save },
    { name: 'Scissors', icon: Scissors },
    { name: 'Search', icon: Search },
    { name: 'Send', icon: Send },
    { name: 'Server', icon: Server },
    { name: 'Share', icon: Share },
    { name: 'Shield', icon: Shield },
    { name: 'ShoppingCart', icon: ShoppingCart },
    { name: 'Shuffle', icon: Shuffle },
    { name: 'Sidebar', icon: Sidebar },
    { name: 'Signal', icon: Signal },
    { name: 'SkipBack', icon: SkipBack },
    { name: 'SkipForward', icon: SkipForward },
    { name: 'Slack', icon: Slack },
    { name: 'Slash', icon: Slash },
    { name: 'Sliders', icon: Sliders },
    { name: 'Smartphone', icon: Smartphone },
    { name: 'Smile', icon: Smile },
    { name: 'Snowflake', icon: Snowflake },
    { name: 'SortAsc', icon: SortAsc },
    { name: 'SortDesc', icon: SortDesc },
    { name: 'Speaker', icon: Speaker },
    { name: 'Star', icon: Star },
    { name: 'StopCircle', icon: StopCircle },
    { name: 'Sun', icon: Sun },
    { name: 'Sunrise', icon: Sunrise },
    { name: 'Sunset', icon: Sunset },
    { name: 'Tablet', icon: Tablet },
    { name: 'Tag', icon: Tag },
    { name: 'Target', icon: Target },
    { name: 'Terminal', icon: Terminal },
    { name: 'Thermometer', icon: Thermometer },
    { name: 'ThumbsDown', icon: ThumbsDown },
    { name: 'ThumbsUp', icon: ThumbsUp },
    { name: 'Ticket', icon: Ticket },
    { name: 'Timer', icon: Timer },
    { name: 'ToggleLeft', icon: ToggleLeft },
    { name: 'ToggleRight', icon: ToggleRight },
    { name: 'TrendingDown', icon: TrendingDown },
    { name: 'TrendingUp', icon: TrendingUp },
    { name: 'Triangle', icon: Triangle },
    { name: 'Truck', icon: Truck },
    { name: 'Tv', icon: Tv },
    { name: 'Twitch', icon: Twitch },
    { name: 'Twitter', icon: Twitter },
    { name: 'Type', icon: Type },
    { name: 'Underline', icon: Underline },
    { name: 'Undo', icon: Undo },
    { name: 'Unlock', icon: Unlock },
    { name: 'Upload', icon: Upload },
    { name: 'UploadCloud', icon: UploadCloud },
    { name: 'Usb', icon: Usb },
    { name: 'Video', icon: Video },
    { name: 'VideoOff', icon: VideoOff },
    { name: 'Voicemail', icon: Voicemail },
    { name: 'Volume1', icon: Volume1 },
    { name: 'Volume2', icon: Volume2 },
    { name: 'VolumeX', icon: VolumeX },
    { name: 'Wallet', icon: Wallet },
    { name: 'Watch', icon: Watch },
    { name: 'Webcam', icon: Webcam },
    { name: 'Wifi', icon: Wifi },
    { name: 'WifiOff', icon: WifiOff },
    { name: 'Wind', icon: Wind },
    { name: 'Youtube', icon: Youtube },
    { name: 'Zap', icon: Zap },
    { name: 'ZoomIn', icon: ZoomIn },
    { name: 'ZoomOut', icon: ZoomOut },
];
